version: '3.8'

services:
  app:
    build: .
    container_name: splitwise-api
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/splitwise
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - db
    networks:
      - splitwise-network

  db:
    image: postgres:16-alpine
    container_name: splitwise-db
    environment:
      - POSTGRES_DB=splitwise
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - splitwise-network

volumes:
  postgres_data:

networks:
  splitwise-network:
    driver: bridge
